// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.0
// source: weather.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetWeatherClient is the client API for GetWeather service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetWeatherClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getWeatherClient struct {
	cc grpc.ClientConnInterface
}

func NewGetWeatherClient(cc grpc.ClientConnInterface) GetWeatherClient {
	return &getWeatherClient{cc}
}

func (c *getWeatherClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.GetWeather/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetWeatherServer is the server API for GetWeather service.
// All implementations must embed UnimplementedGetWeatherServer
// for forward compatibility
type GetWeatherServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGetWeatherServer()
}

// UnimplementedGetWeatherServer must be embedded to have forward compatible implementations.
type UnimplementedGetWeatherServer struct {
}

func (UnimplementedGetWeatherServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetWeatherServer) mustEmbedUnimplementedGetWeatherServer() {}

// UnsafeGetWeatherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetWeatherServer will
// result in compilation errors.
type UnsafeGetWeatherServer interface {
	mustEmbedUnimplementedGetWeatherServer()
}

func RegisterGetWeatherServer(s grpc.ServiceRegistrar, srv GetWeatherServer) {
	s.RegisterService(&GetWeather_ServiceDesc, srv)
}

func _GetWeather_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetWeatherServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GetWeather/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetWeatherServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetWeather_ServiceDesc is the grpc.ServiceDesc for GetWeather service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetWeather_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetWeather",
	HandlerType: (*GetWeatherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetWeather_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
